await import(new URL('../dist/api/get-feed-skeleton.js', import.meta.url))
await import(new URL('../dist/api/get-feed.js', import.meta.url))
await import(new URL('../dist/feed/page-loader.js', import.meta.url))
await import(new URL('../dist/feed/query.js', import.meta.url))
await import(new URL('../dist/hydration/identity.js', import.meta.url))
await import(new URL('../dist/hydration/service.js', import.meta.url))
await import(new URL('../dist/hydration/validation.js', import.meta.url))
await import(new URL('../dist/hydration/views.js', import.meta.url))
